### ISSUE TITLE
Add path mapping support

### ISSUE THREAD

**Issue by must** [CONNECT-platform/coding-blog#18]
We should add path mapping support to map copy source paths to a destination folder structure.

An example configuration would look like:
```javascript
{
  // ...
  plugins: [
    codingBlog({
      assets: [
        'favicon.ico',
        'docs/img',
        { 'src/images/' : '/images' }
      ]
    })
  ]
}
```

**Comment by TysonMN** [comment]
Thanks @must! :)

FWIW, I think this issue is about a particular solution to the discripency I raised in https://github.com/CONNECT-platform/codedoc/issues/18 (in which the GitHub deploy allowed the assets to be anywhere in the underlying repo and then get copied to a different spot for deployment but the deploy to `coding.blog` didn't have a similar layer of indirection).  I probably didn't explain myself clear enough in that issue.

**Comment by TysonMN** [comment]
I have a question about how this feature relates to https://github.com/CONNECT-platform/codedoc/issues/75.

When this feature is implemented, will it be possible to have syntax like this?  Specifically, can the source path include wildcards like `**` that match any subpath?

```js
{
  // ...
  plugins: [
    codingBlog({
      assets: [
        'favicon.ico',
        'docs/img',
        { 'src/posts/**/images/' : '/images' }
      ]
    })
  ]
}
```

**Comment by must** [comment]
I am not sure if this will make it to the first version of the feature. Nevertheless, at some point soon after, I don't see a reason why we wouldn't implement wildcard path support as you mention it.
