### ISSUE TITLE
Add support for specifying redirects

### ISSUE THREAD

**Issue by loreanvictor** [CONNECT-platform/coding-blog#20]
[Quoting](https://github.com/CONNECT-platform/codedoc/issues/47):

> I expect that I will eventually want to "change" publically available URLs to my site. Either I will have a typo in some URL or ? want to change the structure.
>
> Is there a way to specify a list of internal redirects?
>
> As a hypothetical example, I would want to
>
> redirect https://tysonwilliams.coding.blog/this_is_speled_correctly
> to https://tysonwilliams.coding.blog/this_is_spelled_correctly

**Comment by TysonMN** [comment]
FWIW, I would like to use this feature now.

As [you pointed out](https://twitter.com/coding_blog/status/1289120252618579968) @loreanvictor, the title of my recent post was ambiguous.  I clarified it in [this commit](https://github.com/bender2k14/tyson-williams-blog/commit/46216bea7352917dfbefb49d9db66089593be33a).  I would have also prefered to change the name of the markdown file, but I am reluctant to do so until this redirect feature exists.

**Comment by loreanvictor** [comment]
@must do you have any timeframe / plans for this?

**Comment by loreanvictor** [comment]
@must @bender2k14 on second thought, although the preferred method would be sending a 301 (or 302) from the server (CDN), in this case it should be fine (at least for now) to implement a plugin that would cause a client-side redirect (via `http-equiv="refresh"` meta tag). The bonus for this method would be that it would work on any provider and would not be `coding.blog` specific (so it would also work on `gh-pages`).

[Created the issue on `coding-blog-plugin`](https://github.com/CONNECT-platform/coding-blog-plugin/issues/13) for such a component. @bender2k14 @must if you think this should be handled as a server-side status in the long run, please outline your reasons. Otherwise I will be closing this issue when I ship the component on `coding-blog-plugin` (which I suspect will be over the weekend).

**Comment by TysonMN** [comment]
I do not know enough about the HTML protocol to have an opinion between these two solutions.

I once tried to redirect a URL from my wife's old blog to her new blog.  The old blog is hosted by Blogger at a Blogger URL, and the new blog is hosted by Squarespace at a custom URL.  The way I implemented the redirect wasn't good because it was considered suspicious / malicious (I think Google Chrome told me that when following the URL, but I don't remember exactly).

I just want a redirect solution that doesn't causes these types of security tools to flag the behavior as suspicious / malicious.

Maybe loading performance would differ between the two proposed solutions.  However, I don't think performance matters in this case.  The old URL and redirect only exist for backwards compatibility.  If someone wants faster load times, then they can use the target URL of the redirect.

**Comment by loreanvictor** [comment]
> Maybe loading performance would differ between the two proposed solutions. However, I don't think performance matters in this case. The old URL and redirect only exist for backwards compatibility. If someone wants faster load times, then they can use the target URL of the redirect.

Agreed.

> I just want a redirect solution that doesn't causes these types of security tools to flag the behavior as suspicious / malicious.

I don't think there will be any security issues, since this is the way redirects are implemented on GitHub Pages + Jekyll as well (similarly GitHub Pages doesn't provide a server-side solution for redirects). But will look into it as well.

**Comment by loreanvictor** [comment]
Ok the [component is added](https://connect-platform.github.io/coding-blog-plugin/misc#moved-pages) and deployed via `@codedoc/coding-blog-plugin@0.1.11`.
