### ISSUE TITLE
Buggy/Unoptimized rendering in Safari Reader View

### ISSUE THREAD

**Issue by uloco** [CONNECT-platform/coding-blog#38]
When reader view is turned on in safari, the line numbers in code snippets look like this:

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/8818340/97924445-f554b500-1d5f-11eb-9c42-6ff29d8851fa.png">

They should render with a margin to the right I guess ...

**Comment by loreanvictor** [comment]
I doubt the issue is isolated to line-numbering in code-snippets, as no optimization for reader-view has been done so far. So I'm going to rename the issue so that its a bit more encompassing of generally all the issues related to reader-view. Finding other issues and reporting them here would be much appreciated, as would any hints or suggestions of how to optimize for reader view (or PRs ideally?)

**Comment by uloco** [comment]
I think the rest looks fine. It is about using as much as  the right semantic html tags as possible. But for the code snippet parts I am really not sure how to do this at the moment.
