### ISSUE TITLE
Improvements to website content

### ISSUE THREAD

**Issue by sesajad** [CONNECT-platform/coding-blog#5]
I think the TOC of the [coding.blog](coding.blog) is not intuitive. 
1. **Updates**? isn't **Changelog** a better phrase? Then why is it before the **Account**? and in the same section?
2. Isn't it better to have **Blog** outside of the **Account** section?
3. In the README of the boilerplate project, it's mentioned that we can publish the blog simply on Github Pages. I think it must be mentioned in the documentation of [coding.blog](coding.blog) site.

I suggest the following structure

```
Home
For Creators
Changelog
    June 2020
About

Account
Your Blog

Knowledgebase
    Publishing on other platforms
```

**Comment by loreanvictor** [comment]
Blog is part of account because well your blog is part of your account.

The term update is used specifically because it is not a changelog. That section is supposed to host update posts (on the progress of the product).

The proposed layout looks a bit better actually, I will play around a bit with the idea and put some changes up.

I will keep this issue open as a place for gathering feedback on what is confusing / can be better communicated. Specifically, I am curious as to what type of content would people like to see in knowledge base.

**Comment by loreanvictor** [comment]
I am also going to change the issue title for clarification.

**Comment by loreanvictor** [comment]
https://github.com/CONNECT-platform/coding-blog/commit/e5cd5f5c021b5fb2b7c525e341b24d8342779be6
